#####
# Docker compose para iniciar uma infra-estrutura em LAMP utilizando:
# mysql: 8.0.20 - MySQL Community 
# phpmyadmin: : 5.0.2
# PHP: version 7.4.3
# Apache: Apache/2.4.38
# Modulos:  mysqli pdo pdo_mysql
#
# Ultima alteração: 02/06/2020 

version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<super_senha_secreta> 
      - MYSQL_DATABASE=<base inicial mysql> 

  phpmyadmin_app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  web_app:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "/var/www/html/:/var/www/html/"
    ports:
      - "80:80"
    links:
      - db 
